# Generated by Django 3.1.4 on 2021-11-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Изображение категории')),
                ('meta_desc', models.CharField(default='', max_length=63, verbose_name='meta-description')),
                ('meta_title', models.CharField(default='', max_length=63, verbose_name='meta-title')),
                ('meta_h1', models.CharField(default='', max_length=63, verbose_name='meta-h1')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер меню')),
                ('text', models.TextField(blank=True, verbose_name='HTML')),
                ('order', models.IntegerField(blank=True, default=10, null=True, verbose_name='Порядок')),
                ('meta_desc', models.CharField(default='', max_length=63, verbose_name='meta-description')),
                ('meta_title', models.CharField(default='', max_length=63, verbose_name='meta-title')),
                ('meta_h1', models.CharField(default='', max_length=63, verbose_name='meta-h1')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(db_index=True, max_length=250, verbose_name='Название')),
                ('partnumber', models.CharField(db_index=True, max_length=16, verbose_name='Артикул')),
                ('annotation', models.TextField(blank=True, verbose_name='Аннотация')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('epigraph', models.TextField(blank=True, default=None, null=True, verbose_name='Эпиграф')),
                ('epigraph_author', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Автор эпиграфа')),
                ('author', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Картограф')),
                ('material', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Техника')),
                ('source', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Источник')),
                ('carton', models.IntegerField(blank=True, choices=[(0, 'музейный бархат'), (1, 'бархат'), (2, 'лён'), (3, 'другие виды (рисовая бумага)'), (4, 'двойное комбинированное'), (5, 'двойной консервационный картон'), (6, 'консервационный картон'), (7, 'двойной лён')], default=None, null=True, verbose_name='Паспарту')),
                ('glass', models.IntegerField(blank=True, choices=[(0, 'безбликовое стекло'), (1, 'багетное стекло 2 мм')], default=None, null=True, verbose_name='Стекло')),
                ('price', models.IntegerField(db_index=True, verbose_name='Цена')),
                ('sold', models.BooleanField(db_index=True, default=False, verbose_name='Продано')),
                ('mapsize', models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='Размер поля карты')),
                ('framesize', models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='Размер рамы')),
                ('meta_desc', models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='meta-description')),
                ('meta_title', models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='meta-title')),
                ('meta_h1', models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='meta-h1')),
                ('vertical', models.BooleanField(default=True, verbose_name='Вертикально')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.category')),
                ('tags', models.ManyToManyField(blank=True, db_index=True, to='maps.Tag')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Изображение')),
                ('order', models.IntegerField(blank=True, default=10, null=True, verbose_name='Порядок')),
                ('alt', models.CharField(blank=True, max_length=128, verbose_name='Подпись')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maps.product')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
